import ISplatoon3ConstType from "@splatoon3Tracker/interfaces/ISplatoon3ConstType";

export default class Splatoon3Utils {
  public static GetBattleTypes(): ISplatoon3ConstType[] {
    return [
      { type: 'Regular', label: 'レギュラー' },
      { type: 'AnarchyOpenBattle', label: 'バンカラマッチ (オープン)' },
      { type: 'AnarchySeriesBattle', label: 'バンカラマッチ (チャレンジ)' },
      { type: 'XBattle', label: 'Xマッチ' },
      { type: 'Challenge', label: 'イベントバトル' },
      { type: 'SplatfestOpenBattle', label: 'フェスマッチ (オープン)' },
      { type: 'SplatfestProBattle', label: 'フェスマッチ (チャレンジ)' },
      { type: 'TricolorBattle', label: 'トリカラアタック' }
    ]
  }

  public static GetRuleTypes(): ISplatoon3ConstType[] {
    return [
      { type: 'TurfWar', label: 'ナワバリバトル' },
      { type: 'SplatZones', label: 'ガチエリア' },
      { type: 'TowerControl', label: 'ガチヤグラ' },
      { type: 'Rainmaker', label: 'ガチホコ' },
      { type: 'ClamBlitz', label: 'ガチアサリ' }
    ]
  }

  public static GetWeapons(): ISplatoon3ConstType[] {
    return [
      { type: 'SplooshOMatic', label: 'ボールドマーカー' },
      { type: 'NeoSplooshOMatic', label: 'ボールドマーカーネオ' },
      { type: 'SplattershotJr', label: 'わかばシューター' },
      { type: 'CustomSplattershotJr', label: 'もみじシューター' },
      { type: 'SplashOMatic', label: 'シャープマーカー' },
      { type: 'NeoSplashOMatic', label: 'シャープマーカーネオ' },
      { type: 'AerosprayMg', label: 'プロモデラーMG' },
      { type: 'AerosprayRg', label: 'プロモデラーRG' },
      { type: 'Splattershot', label: 'スプラシューター' },
      { type: 'TentatekSplattershot', label: 'スプラシューターコラボ' },
      { type: 'HeroShotReplica', label: 'ヒーローシューター レプリカ' },
      { type: 'OctoShotReplica', label: 'オクタシューター レプリカ' },
      { type: 'OrderShotReplica', label: 'オーダーシューター レプリカ' },
      { type: 'Gal52', label: '.52ガロン' },
      { type: 'Gal52Deco', label: '.52ガロンデコ' },
      { type: 'NZap85', label: 'N-ZAP85' },
      { type: 'NZap89', label: 'N-ZAP89' },
      { type: 'SplattershotPro', label: 'プライムシューター' },
      { type: 'ForgeSplattershotPro', label: 'プライムシューターコラボ' },
      { type: 'Gal96', label: '.96ガロン' },
      { type: 'Gal96Deco', label: '.96ガロンデコ' },
      { type: 'JetSquelcher', label: 'ジェットスイーパー' },
      { type: 'CustomJetSquelcher', label: 'ジェットスイーパーカスタム' },
      { type: 'SplattershotNova', label: 'スペースシューター' },
      { type: 'AnnakiSplattershotNova', label: 'スペースシューターコラボ' },
      { type: 'L3Nozzlenose', label: 'L3リールガン' },
      { type: 'L3NozzlenoseD', label: 'L3リールガンD' },
      { type: 'H3Nozzlenose', label: 'H3リールガン' },
      { type: 'H3NozzlenoseD', label: 'H3リールガンD' },
      { type: 'Squeezer', label: 'ボトルガイザー' },
      { type: 'FoilSqueezer', label: 'ボトルガイザーフォイル' },
      { type: 'CarbonRoller', label: 'カーボンローラー' },
      { type: 'CarbonRollerDeco', label: 'カーボンローラーデコ' },
      { type: 'SplatRoller', label: 'スプラローラー' },
      { type: 'KrakOnSplatRoller', label: 'スプラローラーコラボ' },
      { type: 'OrderRollerReplica', label: 'オーダーローラー レプリカ' },
      { type: 'DynamoRoller', label: 'ダイナモローラー' },
      { type: 'GoldDynamoRoller', label: 'ダイナモローラーテスラ' },
      { type: 'FlingzaRoller', label: 'ヴァリアブルローラー' },
      { type: 'FoilFlingzaRoller', label: 'ヴァリアブルローラーフォイル' },
      { type: 'BigSwigRoller', label: 'ワイドローラー' },
      { type: 'BigSwigRollerExpress', label: 'ワイドローラーコラボ' },
      { type: 'ClassicSquiffer', label: 'スクイックリンα' },
      { type: 'NewSquiffer', label: 'スクイックリンβ' },
      { type: 'SplatCharger', label: 'スプラチャージャー' },
      { type: 'ZFSplatCharger', label: 'スプラチャージャーコラボ' },
      { type: 'OrderChargerReplica', label: 'オーダーチャージャー レプリカ' },
      { type: 'Splatterscope', label: 'スプラスコープ' },
      { type: 'ZFSplatterscope', label: 'スプラスコープコラボ' },
      { type: 'ELiter4K', label: 'リッター4K' },
      { type: 'CustomELiter4K', label: 'リッター4Kカスタム' },
      { type: 'ELiter4KScope', label: '4Kスコープ' },
      { type: 'CustomELiter4KScope', label: '4Kスコープカスタム' },
      { type: 'Bamboozler14MkI', label: '14式竹筒銃・甲' },
      { type: 'Bamboozler14MkIi', label: '14式竹筒銃・乙' },
      { type: 'GooTuber', label: 'ソイチューバー' },
      { type: 'CustomGooTuber', label: 'ソイチューバーカスタム' },
      { type: 'Snipewriter5H', label: 'R-PEN/5H' },
      { type: 'Snipewriter5B', label: 'R-PEN/5B' },
      { type: 'Slosher', label: 'バケットスロッシャー' },
      { type: 'SlosherDeco', label: 'バケットスロッシャーデコ' },
      { type: 'OrderSlosherReplica', label: 'オーダースロッシャー レプリカ' },
      { type: 'TriSlosher', label: 'ヒッセン' },
      { type: 'TriSlosherNouveau', label: 'ヒッセン・ヒュー' },
      { type: 'SloshingMachine', label: 'スクリュースロッシャー' },
      { type: 'SloshingMachineNeo', label: 'スクリュースロッシャーネオ' },
      { type: 'Bloblobber', label: 'オーバーフロッシャー' },
      { type: 'BloblobberDeco', label: 'オーバーフロッシャーデコ' },
      { type: 'Explosher', label: 'エクスプロッシャー' },
      { type: 'CustomExplosher', label: 'エクスプロッシャーカスタム' },
      { type: 'DreadWringer', label: 'モップリン' },
      { type: 'DreadWringerD', label: 'モップリンD' },
      { type: 'MiniSplatling', label: 'スプラスピナー' },
      { type: 'ZinkMiniSplatling', label: 'スプラスピナーコラボ' },
      { type: 'HeavySplatling', label: 'バレルスピナー' },
      { type: 'HeavySplatlingDeco', label: 'バレルスピナーデコ' },
      { type: 'OrderSplatlingReplica', label: 'オーダースピナー レプリカ' },
      { type: 'HydraSplatling', label: 'ハイドラント' },
      { type: 'CustomHydraSplatling', label: 'ハイドラントカスタム' },
      { type: 'BallpointSplatling', label: 'クーゲルシュライバー' },
      { type: 'BallpointSplatlingNouveau', label: 'クーゲルシュライバー・ヒュー' },
      { type: 'Nautilus47', label: 'ノーチラス47' },
      { type: 'Nautilus79', label: 'ノーチラス79' },
      { type: 'HeavyEditSplatling', label: 'イグザミナー' },
      { type: 'HeavyEditSplatlingNouveau', label: 'イグザミナー・ヒュー' },
      { type: 'DappleDualies', label: 'スパッタリー' },
      { type: 'DappleDualiesNouveau', label: 'スパッタリー・ヒュー' },
      { type: 'SplatDualies', label: 'スプラマニューバー' },
      { type: 'EnperrySplatDualies', label: 'スプラマニューバーコラボ' },
      { type: 'OrderDualieReplicas', label: 'オーダーマニューバー レプリカ' },
      { type: 'GloogaDualies', label: 'ケルビン525' },
      { type: 'GloogaDualiesDeco', label: 'ケルビン525デコ' },
      { type: 'DualieSquelchers', label: 'デュアルスイーパー' },
      { type: 'CustomDualieSquelchers', label: 'デュアルスイーパーカスタム' },
      { type: 'DarkTetraDualies', label: 'クアッドホッパーブラック' },
      { type: 'LightTetraDualies', label: 'クアッドホッパーホワイト' },
      { type: 'DouserDualiesFf', label: 'ガエンFF' },
      { type: 'CustomDouserDualiesFf', label: 'ガエンFFカスタム' },
      { type: 'SplatBrella', label: 'パラシェルター' },
      { type: 'SorellaBrella', label: 'パラシェルターソレーラ' },
      { type: 'OrderBrellaReplica', label: 'オーダーシェルター レプリカ' },
      { type: 'TentaBrella', label: 'キャンピングシェルター' },
      { type: 'TentaSorellaBrella', label: 'キャンピングシェルターソレーラ' },
      { type: 'UndercoverBrella', label: 'スパイガジェット' },
      { type: 'UndercoverSorellaBrella', label: 'スパイガジェットソレーラ' },
      { type: 'RecycledBrella24MkI', label: '24式張替傘・甲' },
      { type: 'RecycledBrella24MkIi', label: '24式張替傘・乙' },
      { type: 'LunaBlaster', label: 'ノヴァブラスター' },
      { type: 'LunaBlasterNeo', label: 'ノヴァブラスターネオ' },
      { type: 'OrderBlasterReplica', label: 'オーダーブラスター レプリカ' },
      { type: 'Blaster', label: 'ホットブラスター' },
      { type: 'CustomBlaster', label: 'ホットブラスターカスタム' },
      { type: 'RangeBlaster', label: 'ロングブラスター' },
      { type: 'CustomRangeBlaster', label: 'ロングブラスターカスタム' },
      { type: 'ClashBlaster', label: 'クラッシュブラスター' },
      { type: 'ClashBlasterNeo', label: 'クラッシュブラスターネオ' },
      { type: 'RapidBlaster', label: 'ラピッドブラスター' },
      { type: 'RapidBlasterDeco', label: 'ラピッドブラスターデコ' },
      { type: 'RapidBlasterPro', label: 'Rブラスターエリート' },
      { type: 'RapidBlasterProDeco', label: 'Rブラスターエリートデコ' },
      { type: 'SBlast92', label: 'S-BLAST92' },
      { type: 'SBlast91', label: 'S-BLAST91' },
      { type: 'Inkbrush', label: 'パブロ' },
      { type: 'InkbrushNouveau', label: 'パブロ・ヒュー' },
      { type: 'Octobrush', label: 'ホクサイ' },
      { type: 'OctobrushNouveau', label: 'ホクサイ・ヒュー' },
      { type: 'OrderbrushReplica', label: 'オーダーブラシ レプリカ' },
      { type: 'Painbrush', label: 'フィンセント' },
      { type: 'PainbrushNouveau', label: 'フィンセント・ヒュー' },
      { type: 'TriStringer', label: 'トライストリンガー' },
      { type: 'InklineTriStringer', label: 'トライストリンガーコラボ' },
      { type: 'OrderStringerReplica', label: 'オーダーストリンガー レプリカ' },
      { type: 'ReefLux450', label: 'LACT-450' },
      { type: 'ReefLux450Deco', label: 'LACT-450デコ' },
      { type: 'WellstringV', label: 'フルイドV' },
      { type: 'CustomWellstringV', label: 'フルイドVカスタム' },
      { type: 'SplatanaStamper', label: 'ジムワイパー' },
      { type: 'SplatanaStamperNouveau13', label: 'ジムワイパー・ヒュー' },
      { type: 'OrderSplatanaReplica', label: 'オーダーワイパー レプリカ' },
      { type: 'SplatanaWiper', label: 'ドライブワイパー' },
      { type: 'SplatanaWiperDeco', label: 'ドライブワイパーデコ' },
      { type: 'MintDecavitator', label: 'デンタルワイパーミント' },
      { type: 'CharcoalDecavitator', label: 'デンタルワイパースミ' }
    ]
  }
}
